# Generated by Django 3.2.5 on 2021-08-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteblock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='colors',
        ),
        migrations.AddField(
            model_name='noteblock',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
