# Generated by Django 3.2.5 on 2021-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteblock', '0002_auto_20210825_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteblock',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
