# Generated by Django 3.2.5 on 2021-08-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteblock', '0004_alter_noteblock_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteblock',
            name='color',
            field=models.CharField(choices=[('dark', 'dark'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], max_length=11),
        ),
    ]
